//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RY.PlugIns.SimWCFService.RYWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/RYWcfService", ConfigurationName="RYWCF.IRYSimpleWcfService")]
    public interface IRYSimpleWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/RYWcfService/IRYSimpleWcfService/GetTime", ReplyAction="http://localhost:8080/RYWcfService/IRYSimpleWcfService/GetTimeResponse")]
        System.DateTime GetTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/RYWcfService/IRYSimpleWcfService/GetTime", ReplyAction="http://localhost:8080/RYWcfService/IRYSimpleWcfService/GetTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/RYWcfService/IRYSimpleWcfService/Add", ReplyAction="http://localhost:8080/RYWcfService/IRYSimpleWcfService/AddResponse")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/RYWcfService/IRYSimpleWcfService/Add", ReplyAction="http://localhost:8080/RYWcfService/IRYSimpleWcfService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRYSimpleWcfServiceChannel : RY.PlugIns.SimWCFService.RYWCF.IRYSimpleWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RYSimpleWcfServiceClient : System.ServiceModel.ClientBase<RY.PlugIns.SimWCFService.RYWCF.IRYSimpleWcfService>, RY.PlugIns.SimWCFService.RYWCF.IRYSimpleWcfService {
        
        public RYSimpleWcfServiceClient() {
        }
        
        public RYSimpleWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RYSimpleWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RYSimpleWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RYSimpleWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetTime() {
            return base.Channel.GetTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetTimeAsync() {
            return base.Channel.GetTimeAsync();
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
    }
}
